### ISSUE TITLE
Cannot import grafana dashboard with variables

### ISSUE THREAD

**Issue by f0o** [GoogleCloudPlatform/monitoring-dashboard-samples#772]
It seems that any query that uses a dashboard variable cannot be imported and leads to empty queries.

such as:
```
            "promQLQuery": {
              "expr": "avg(streamservice_latency{quantile=\"0.999\",pod=~\"$pod\"})",
              "projectName": "obsidian-1929",
              "step": "$__interval"
            },
```

will lead to an empty value:
```
            {
                "widget": {
                    "scorecard": {
                        "gaugeView": {
                            "lowerBound": 0,
                            "upperBound": 100
                        },
                        "thresholds": [],
                        "timeSeriesQuery": {}
                    },
                    "title": "99%ile (24h)"
                },
                "xPos": 20,
                "yPos": 0,
                "height": 6,
                "width": 4
            },
```

The report.json contains following warnings:
```
                "Template variable 'pod' was skipped because queries that start with '' are not supported",
                "panel undefined target at index 0 does not have an expression",
                "panel undefined target at index 0 does not have an expression",
                "panel Discarded Trades (24h) target at index 0 does not have an expression",
                "panel 50%ile (24h) target at index 0 does not have an expression",
                "panel 90%ile (24h) target at index 0 does not have an expression",
                "panel 95%ile (24h) target at index 0 does not have an expression",
                "panel 99%ile (24h) target at index 0 does not have an expression",
                "panel Discards/Sec target at index 0 does not have an expression",
                "panel Discards/Sec target at index 0 does not have an expression",
                "panel Discards/Sec target at index 0 does not have an expression",
                "panel Latency target at index 0 does not have an expression"
```

**Comment by yqlu** [comment]
@stevezease can you take a look?

**Comment by stevezease** [comment]
The importer currently expects expressions to be under `panels[n].targets[m].expr`. Based on the example given, it seems that expressions were provided under (what I presume to be) `panels[n].targets[m].promQLQuery.expr`. 
At the time of implementation, the importer was not designed to locate expressions there, resulting in the warnings. 

Digging around I wasn't able to locate much on expressions in the above mentioned format.
If you could provide a bit more information/context on the Grafana JSON used, I'd be happy to look into this further.

**Comment by f0o** [comment]
it seems that all grafana 11.2.0 (+ stackdriver plugin version 11.2.0-pre ) dashboards have `panels[n].targets[m].promQLQuery.expr` structure. Maybe that's just an incompatibility with the newer grafana/stackdriver versions then?

**Comment by stevezease** [comment]
Ah, it appears this is the dashboard schema for dashboards with the Google Cloud Monitoring datasource.

The importer is currently only scoped to handle Prometheus data sources. As this is not a defect with the current behavior, this would need to be a feature request which I can notify our stakeholders of. 
However, because we haven't been building out the importer to support additional functionality, I can't guarantee that the request will be implemented.

One workaround may be along the lines of exporting a JSON from the prometheus datasource and then replacing the promql queries in the output json with the promQL from the cloud monitoring DS dashboard

Alternatively, if familiar with npm/typescript, another potential idea may be to make changes to your own local copy of the importer and rebuilding.
The change would be along the lines of updating the following logic to be also use `target.promQLQuery.expr` also:
https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/blob/master/scripts/dashboard-importer/src/dashboards/converter/expression.ts#L33
Though as I am not entirely familiar with the exact schema of your dashboard, please proceed at your own discretion.
